name: Deploy (ECS)

on:
  push:
    branches: ["main"]
    paths:
      - "backend-service/**"
      - "ecs/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "615340784692"
  ECR_REPOSITORY: cloud-data-platform-dev-backend-service
  ECS_CLUSTER: cloud-data-platform-dev-cluster
  ECS_SERVICE: cloud-data-platform-dev-backend-service
  CONTAINER_NAME: backend-service
  TASK_DEFINITION: ecs/task-definition.json

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615340784692:role/cloud-data-platform-dev-github-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate git.properties for actuator info
        run: |
          mkdir -p backend-service/src/main/resources
          cat > backend-service/src/main/resources/git.properties <<EOF
          git.branch=${GITHUB_REF_NAME}
          git.commit.id=${GITHUB_SHA}
          git.commit.time=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          git.commit.id.abbrev=${GITHUB_SHA:0:7}
          EOF


      - name: Build and push image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./backend-service
          file: ./backend-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Render task definition (swap image)
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
